app/routes/institutions.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.models import Institution, Position
from app.forms import InstitutionForm
from app import db
from flask_login import login_required

bp = Blueprint('institutions', __name__, url_prefix='/institutions')


@bp.route('/')
@login_required
def index():
    """List all institutions"""
    page = request.args.get('page', 1, type=int)
    per_page = 50
    
    # Search functionality
    search = request.args.get('search', '')
    query = Institution.query
    
    if search:
        search_pattern = f'%{search}%'
        query = query.filter(
            db.or_(
                Institution.institution_code.ilike(search_pattern),
                Institution.institution_name.ilike(search_pattern),
                Institution.country_code.ilike(search_pattern)
            )
        )
    
    # Sort by institution name
    query = query.order_by(Institution.institution_name)
    
    institutions = query.paginate(page=page, per_page=per_page, error_out=False)
    
    return render_template('institutions/index.html', 
                         institutions=institutions, 
                         search=search)


@bp.route('/<institution_code>')
@login_required
def detail(institution_code):
    """View institution details including all positions"""
    institution = Institution.query.get_or_404(institution_code)
    
    # Get all positions in this institution
    positions = Position.query.filter_by(
        institution_code=institution_code
    ).order_by(Position.position_title).all()
    
    return render_template('institutions/detail.html',
                         institution=institution,
                         positions=positions)


@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    """Create new institution"""
    form = InstitutionForm()
    
    if form.validate_on_submit():
        institution = Institution(
            institution_code=form.institution_code.data,
            institution_name=form.institution_name.data,
            institution_type=form.institution_type.data,
            country_code=form.country_code.data,
            description=form.description.data
        )
        
        db.session.add(institution)
        db.session.commit()
        
        flash(f'Institution {institution.institution_name} created', 'success')
        return redirect(url_for('institutions.detail', 
                              institution_code=institution.institution_code))
    
    return render_template('institutions/create.html', form=form)


@bp.route('/<institution_code>/edit', methods=['GET', 'POST'])
@login_required
def edit(institution_code):
    """Edit existing institution"""
    institution = Institution.query.get_or_404(institution_code)
    form = InstitutionForm(obj=institution)
    form.edit_mode = True
    
    if form.validate_on_submit():
        institution.institution_name = form.institution_name.data
        institution.institution_type = form.institution_type.data
        institution.country_code = form.country_code.data
        institution.description = form.description.data
        
        db.session.commit()
        
        flash(f'Institution {institution.institution_name} updated', 'success')
        return redirect(url_for('institutions.detail', 
                              institution_code=institution_code))
    
    return render_template('institutions/edit.html', form=form, institution=institution)


@bp.route('/<institution_code>/delete', methods=['POST'])
@login_required
def delete(institution_code):
    """Delete institution (will cascade delete positions and tenures)"""
    institution = Institution.query.get_or_404(institution_code)
    name = institution.institution_name
    
    # Check if institution has positions
    position_count = Position.query.filter_by(institution_code=institution_code).count()
    
    if position_count > 0:
        flash(f'Cannot delete {name}: institution has {position_count} positions. Delete positions first.', 'error')
        return redirect(url_for('institutions.detail', institution_code=institution_code))
    
    db.session.delete(institution)
    db.session.commit()
    
    flash(f'Institution {name} deleted', 'success')
    return redirect(url_for('institutions.index'))

app/routes/positions.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.models import Position, Institution, Tenure, Actor
from app.forms import PositionForm, TenureForm
from app import db
from datetime import date
from flask_login import login_required

bp = Blueprint('positions', __name__, url_prefix='/positions')


@bp.route('/')
@login_required
def index():
    """List all positions"""
    page = request.args.get('page', 1, type=int)
    per_page = 50
    
    # Search functionality
    search = request.args.get('search', '')
    query = Position.query
    
    if search:
        search_pattern = f'%{search}%'
        query = query.filter(
            db.or_(
                Position.position_code.ilike(search_pattern),
                Position.position_title.ilike(search_pattern)
            )
        )
    
    # Sort by position title
    query = query.order_by(Position.position_title)
    
    positions = query.paginate(page=page, per_page=per_page, error_out=False)
    
    return render_template('positions/index.html', positions=positions, search=search)


@bp.route('/<position_code>')
@login_required
def detail(position_code):
    """View position details including tenure history"""
    position = Position.query.get_or_404(position_code)
    
    # Get all tenures for this position
    tenures = Tenure.query.filter_by(position_code=position_code).order_by(
        Tenure.tenure_start.desc()
    ).all()
    
    # Get current holder
    current_holder = position.get_current_holder()
    
    return render_template('positions/detail.html',
                         position=position,
                         tenures=tenures,
                         current_holder=current_holder)


@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    """Create new position"""
    form = PositionForm()
    
    # Populate institution choices
    institutions = Institution.query.order_by(Institution.institution_name).all()
    form.institution_code.choices = [
        (inst.institution_code, f'{inst.institution_code} - {inst.institution_name}')
        for inst in institutions
    ]
    
    if form.validate_on_submit():
        position = Position(
            position_code=form.position_code.data,
            position_title=form.position_title.data,
            institution_code=form.institution_code.data,
            hierarchy_level=form.hierarchy_level.data,
            description=form.description.data
        )
        
        db.session.add(position)
        db.session.commit()
        
        flash(f'Position {position.position_title} created', 'success')
        return redirect(url_for('positions.detail', position_code=position.position_code))
    
    return render_template('positions/create.html', form=form)


@bp.route('/<position_code>/edit', methods=['GET', 'POST'])
@login_required
def edit(position_code):
    """Edit existing position"""
    position = Position.query.get_or_404(position_code)
    form = PositionForm(obj=position)
    form.edit_mode = True
    
    # Populate institution choices
    institutions = Institution.query.order_by(Institution.institution_name).all()
    form.institution_code.choices = [
        (inst.institution_code, f'{inst.institution_code} - {inst.institution_name}')
        for inst in institutions
    ]
    
    if form.validate_on_submit():
        position.position_title = form.position_title.data
        position.institution_code = form.institution_code.data
        position.hierarchy_level = form.hierarchy_level.data
        position.description = form.description.data
        
        db.session.commit()
        
        flash(f'Position {position.position_title} updated', 'success')
        return redirect(url_for('positions.detail', position_code=position_code))
    
    return render_template('positions/edit.html', form=form, position=position)


@bp.route('/<position_code>/delete', methods=['POST'])
@login_required
def delete(position_code):
    """Delete position (will cascade delete tenures)"""
    position = Position.query.get_or_404(position_code)
    title = position.position_title
    
    db.session.delete(position)
    db.session.commit()
    
    flash(f'Position {title} deleted', 'success')
    return redirect(url_for('positions.index'))


@bp.route('/<position_code>/assign', methods=['GET', 'POST'])
@login_required
def assign_tenure(position_code):
    """Assign an actor to this position (create tenure)"""
    position = Position.query.get_or_404(position_code)
    form = TenureForm()
    
    # Populate actor choices
    actors = Actor.query.order_by(Actor.surname, Actor.given_name).all()
    form.actor_id.choices = [
        (actor.actor_id, f'{actor.actor_id} - {actor.get_display_name()}')
        for actor in actors
    ]
    
    # Set position (readonly)
    form.position_code.choices = [(position.position_code, position.position_title)]
    form.position_code.data = position.position_code
    
    if form.validate_on_submit():
        tenure = Tenure(
            actor_id=form.actor_id.data,
            position_code=position.position_code,
            tenure_start=form.tenure_start.data,
            tenure_end=form.tenure_end.data
        )
        
        db.session.add(tenure)
        db.session.commit()
        
        actor = Actor.query.get(form.actor_id.data)
        flash(f'{actor.get_display_name()} assigned to {position.position_title}', 'success')
        return redirect(url_for('positions.detail', position_code=position_code))
    
    return render_template('positions/assign.html', form=form, position=position)


@bp.route('/tenure/<int:tenure_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_tenure(tenure_id):
    """Edit existing tenure"""
    tenure = Tenure.query.get_or_404(tenure_id)
    form = TenureForm(obj=tenure)
    form.tenure_id = tenure_id
    
    # Populate actor choices
    actors = Actor.query.order_by(Actor.surname, Actor.given_name).all()
    form.actor_id.choices = [
        (actor.actor_id, f'{actor.actor_id} - {actor.get_display_name()}')
        for actor in actors
    ]
    
    # Populate position choices
    positions = Position.query.order_by(Position.position_title).all()
    form.position_code.choices = [
        (pos.position_code, f'{pos.position_code} - {pos.position_title}')
        for pos in positions
    ]
    
    if form.validate_on_submit():
        tenure.actor_id = form.actor_id.data
        tenure.position_code = form.position_code.data
        tenure.tenure_start = form.tenure_start.data
        tenure.tenure_end = form.tenure_end.data
        
        db.session.commit()
        
        flash('Tenure updated', 'success')
        return redirect(url_for('positions.detail', position_code=tenure.position_code))
    
    return render_template('positions/edit_tenure.html', form=form, tenure=tenure)


@bp.route('/tenure/<int:tenure_id>/delete', methods=['POST'])
@login_required
def delete_tenure(tenure_id):
    """Delete tenure"""
    tenure = Tenure.query.get_or_404(tenure_id)
    position_code = tenure.position_code
    
    db.session.delete(tenure)
    db.session.commit()
    
    flash('Tenure deleted', 'success')
    return redirect(url_for('positions.detail', position_code=position_code))

app/templates/institutions/create.html
{% extends "base.html" %}

{% block title %}Create Institution - Global Narratives{% endblock %}

{% block content %}
<div class="container">
    <!-- Page Header -->
    <div class="flex items-center justify-between mb-lg">
        <h1>Create Institution</h1>
        <a href="{{ url_for('institutions.index') }}" class="btn btn-secondary">Back to Institutions</a>
    </div>

    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Institution Information</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="{{ url_for('institutions.create') }}">
                {{ form.hidden_tag() }}
                
                <!-- Institution Code -->
                <div class="form-group">
                    <label class="form-label" for="institution_code">Institution Code</label>
                    {{ form.institution_code(class="form-input", id="institution_code", placeholder="e.g., vie.cbk, jpn.com.mde.002") }}
                    <small class="text-dim">CIE hierarchical code</small>
                    {% if form.institution_code.errors %}
                        <div class="text-warning">{{ form.institution_code.errors[0] }}</div>
                    {% endif %}
                </div>
                
                <!-- Institution Name -->
                <div class="form-group">
                    <label class="form-label" for="institution_name">Institution Name</label>
                    {{ form.institution_name(class="form-input", id="institution_name", placeholder="e.g., Central Bank of Vietnam") }}
                    <small class="text-dim">Full name in natural language</small>
                    {% if form.institution_name.errors %}
                        <div class="text-warning">{{ form.institution_name.errors[0] }}</div>
                    {% endif %}
                </div>
                
                <!-- Institution Type & Country -->
                <div class="grid grid-cols-2">
                    <div class="form-group">
                        <label class="form-label" for="institution_type">Institution Type (Optional)</label>
                        {{ form.institution_type(class="form-input", id="institution_type", placeholder="e.g., Government, Corporate, NGO") }}
                        <small class="text-dim">Encoded in CIE code but extracted for display</small>
                    </div>
                    
                    <div class="form-group">
                        <label class="form-label" for="country_code">Country Code (Optional)</label>
                        {{ form.country_code(class="form-input", id="country_code", placeholder="e.g., vie, jpn, usa") }}
                        <small class="text-dim">ISO 3-letter code</small>
                    </div>
                </div>
                
                <!-- Description -->
                <div class="form-group">
                    <label class="form-label" for="description">Description (Optional)</label>
                    {{ form.description(class="form-textarea", id="description", rows="4", placeholder="Additional context about this institution") }}
                </div>
                
                <!-- Form Actions -->
                <div class="flex gap-md mt-lg">
                    <button type="submit" class="btn btn-primary">Create Institution</button>
                    <a href="{{ url_for('institutions.index') }}" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/institutions/detail.html
{% extends "base.html" %}

{% block title %}{{ institution.institution_name }} - Global Narratives{% endblock %}

{% block content %}
<div class="container">
    <!-- Page Header -->
    <div class="flex items-center justify-between mb-lg">
        <h1>{{ institution.institution_name }}</h1>
        <div class="flex gap-md">
            <a href="{{ url_for('institutions.edit', institution_code=institution.institution_code) }}" class="btn btn-secondary">Edit Institution</a>
            <form method="POST" action="{{ url_for('institutions.delete', institution_code=institution.institution_code) }}" style="display: inline;" onsubmit="return confirm('Are you sure you want to delete this institution? This will also delete all associated positions and tenures.');">
                <button type="submit" class="btn btn-warning">Delete</button>
            </form>
            <a href="{{ url_for('institutions.index') }}" class="btn btn-secondary">Back to Institutions</a>
        </div>
    </div>

    <!-- Institution Info Card -->
    <div class="card mb-lg">
        <div class="card-header">
            <h2 class="card-title">Institution Information</h2>
            <span class="badge badge-active">{{ institution.institution_code }}</span>
        </div>
        <div class="card-body">
            <div class="grid grid-cols-3 mb-lg">
                <div class="metric">
                    <span class="metric-label">Institution Code</span>
                    <span class="metric-value" style="font-size: 1.25rem;">{{ institution.institution_code }}</span>
                </div>
                <div class="metric">
                    <span class="metric-label">Type</span>
                    <span class="metric-value" style="font-size: 1.25rem;">{{ institution.institution_type or 'N/A' }}</span>
                </div>
                <div class="metric">
                    <span class="metric-label">Country</span>
                    <span class="metric-value" style="font-size: 1.25rem;">{{ institution.country_code.upper() if institution.country_code else 'N/A' }}</span>
                </div>
            </div>
            
            {% if institution.description %}
            <div>
                <div class="metric-label">Description</div>
                <p class="text-secondary">{{ institution.description }}</p>
            </div>
            {% endif %}
        </div>
    </div>

    <!-- Positions Card -->
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Positions ({{ positions|length }})</h2>
            <a href="{{ url_for('positions.create') }}" class="btn btn-primary" style="font-size: 0.875rem;">Create Position</a>
        </div>
        <div class="card-body">
            {% if positions %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Position Code</th>
                            <th>Title</th>
                            <th>Hierarchy Level</th>
                            <th>Current Holder</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for position in positions %}
                        <tr>
                            <td class="text-accent">{{ position.position_code }}</td>
                            <td>
                                <a href="{{ url_for('positions.detail', position_code=position.position_code) }}" class="text-primary">
                                    {{ position.position_title }}
                                </a>
                            </td>
                            <td class="text-secondary">{{ position.hierarchy_level or '—' }}</td>
                            <td>
                                {% set holder = position.get_current_holder() %}
                                {% if holder %}
                                    <a href="{{ url_for('actors.detail', actor_id=holder.actor_id) }}" class="text-accent">
                                        {{ holder.get_display_name() }}
                                    </a>
                                {% else %}
                                    <span class="badge badge-resolved">Vacant</span>
                                {% endif %}
                            </td>
                            <td>
                                <div class="flex gap-sm">
                                    <a href="{{ url_for('positions.detail', position_code=position.position_code) }}" class="btn btn-secondary" style="font-size: 0.75rem; padding: 0.25rem 0.75rem;">View</a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="text-secondary">No positions defined for this institution.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/institutions/edit.html
{% extends "base.html" %}

{% block title %}Edit Institution - Global Narratives{% endblock %}

{% block content %}
<div class="container">
    <!-- Page Header -->
    <div class="flex items-center justify-between mb-lg">
        <h1>Edit Institution</h1>
        <a href="{{ url_for('institutions.detail', institution_code=institution.institution_code) }}" class="btn btn-secondary">Back to Institution</a>
    </div>

    <div class="card">
        <div class="card-header">
            <h2 class="card-title">{{ institution.institution_name }}</h2>
            <span class="badge badge-pending">{{ institution.institution_code }}</span>
        </div>
        <div class="card-body">
            <form method="POST" action="{{ url_for('institutions.edit', institution_code=institution.institution_code) }}">
                {{ form.hidden_tag() }}
                
                <!-- Institution Code (readonly) -->
                <div class="form-group">
                    <label class="form-label" for="institution_code">Institution Code</label>
                    <input type="text" class="form-input" id="institution_code" value="{{ institution.institution_code }}" readonly>
                    <small class="text-dim">Cannot be changed after creation</small>
                </div>
                
                <!-- Institution Name -->
                <div class="form-group">
                    <label class="form-label" for="institution_name">Institution Name</label>
                    {{ form.institution_name(class="form-input", id="institution_name") }}
                    {% if form.institution_name.errors %}
                        <div class="text-warning">{{ form.institution_name.errors[0] }}</div>
                    {% endif %}
                </div>
                
                <!-- Institution Type & Country -->
                <div class="grid grid-cols-2">
                    <div class="form-group">
                        <label class="form-label" for="institution_type">Institution Type (Optional)</label>
                        {{ form.institution_type(class="form-input", id="institution_type") }}
                    </div>
                    
                    <div class="form-group">
                        <label class="form-label" for="country_code">Country Code (Optional)</label>
                        {{ form.country_code(class="form-input", id="country_code") }}
                    </div>
                </div>
                
                <!-- Description -->
                <div class="form-group">
                    <label class="form-label" for="description">Description (Optional)</label>
                    {{ form.description(class="form-textarea", id="description", rows="4") }}
                </div>
                
                <!-- Form Actions -->
                <div class="flex gap-md mt-lg">
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                    <a href="{{ url_for('institutions.detail', institution_code=institution.institution_code) }}" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/institutions/index.html
<!-- {% extends "base.html" %}

{% block title %}Institutions - Global Narratives{% endblock %}

{% block content %}
<div class="container">
   
    <div class="flex items-center justify-between mb-lg">
        <h1>Institutions</h1>
        <a href="{{ url_for('institutions.create') }}" class="btn btn-primary">Create Institution</a>
    </div>

   
    <div class="card mb-lg">
        <div class="card-header">
            <h3 class="card-title">Search Institutions</h3>
        </div>
        <div class="card-body">
            <form method="GET" action="{{ url_for('institutions.index') }}">
                <div class="form-group">
                    <label class="form-label" for="search">Search</label>
                    <input type="text" id="search" name="search" class="form-input" placeholder="Search by code, name, or country" value="{{ search }}">
                </div>
                <div class="flex gap-md">
                    <button type="submit" class="btn btn-primary">Search</button>
                    <a href="{{ url_for('institutions.index') }}" class="btn btn-secondary">Clear</a>
                </div>
            </form>
        </div>
    </div>


    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Institutions ({{ institutions.total }})</h3>
            <span class="text-secondary">Page {{ institutions.page }} of {{ institutions.pages }}</span>
        </div>
        <div class="card-body">
            {% if institutions.items %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Institution Code</th>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Country</th>
                            <th>Positions</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for institution in institutions.items %}
                        <tr>
                            <td class="text-accent">{{ institution.institution_code }}</td>
                            <td>
                                <a href="{{ url_for('institutions.detail', institution_code=institution.institution_code) }}" class="text-primary">
                                    {{ institution.institution_name }}
                                </a>
                            </td>
                            <td class="text-secondary">{{ institution.institution_type or '—' }}</td>
                            <td class="text-secondary">{{ institution.country_code.upper() if institution.country_code else '—' }}</td>
                            <td class="text-secondary">{{ institution.positions|length }}</td>
                            <td>
                                <div class="flex gap-sm">
                                    <a href="{{ url_for('institutions.detail', institution_code=institution.institution_code) }}" class="btn btn-secondary" style="font-size: 0.75rem; padding: 0.25rem 0.75rem;">View</a>
                                    <a href="{{ url_for('institutions.edit', institution_code=institution.institution_code) }}" class="btn btn-secondary" style="font-size: 0.75rem; padding: 0.25rem 0.75rem;">Edit</a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

             
                {% if institutions.pages > 1 %}
                <div class="flex items-center justify-between mt-lg border-top" style="padding-top: var(--space-md);">
                    <div class="text-secondary">
                        Showing {{ ((institutions.page - 1) * institutions.per_page) + 1 }} to {{ min(institutions.page * institutions.per_page, institutions.total) }} of {{ institutions.total }}
                    </div>
                    <div class="flex gap-sm">
                        {% if institutions.has_prev %}
                            <a href="{{ url_for('institutions.index', page=institutions.prev_num, search=search) }}" class="btn btn-secondary">Previous</a>
                        {% endif %}
                        {% if institutions.has_next %}
                            <a href="{{ url_for('institutions.index', page=institutions.next_num, search=search) }}" class="btn btn-secondary">Next</a>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
            {% else %}
                <p class="text-secondary">No institutions found.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %} -->